language: perl
perl:
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"
    - "5.22"
    - "5.24"
    - "5.26"
    - "5.28"
    - "5.30"
    - "5.30-thr"
    - "dev"
    - "dev-thr"
    - "blead"
matrix:
    allow_failures:
        - perl: "blead"
    include:
        - perl: "5.24"
          env: MATH_BIGINT_VERSION=1.999813
sudo: false
before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - '[ -n "$MATH_BIGINT_VERSION" ] && cpanm -n Math::BigInt@"$MATH_BIGINT_VERSION" || true'
    - build-dist
    - cd $BUILD_DIR
install:
    - cpan-install --deps
notifications:
    email:
        on_success: always
        on_failure: always
